######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 16:52:01 2013
######################################################################

TEMPLATE = app
TARGET = gotocell1
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += gotocelldialog.h
SOURCES += gotocelldialog.cpp main.cpp
